#!/bin/bash

set -e

BASE_DIR=`pwd`
# https://github.com/docker/docker/issues/8395#issuecomment-57918396
HOST_IP=`ip route show 0.0.0.0/0 | grep -Eo 'via \S+' | awk '{ print $2 }'`
export DOCKER_HOST=tcp://$HOST_IP:2377
export ETCDCTL_ENDPOINT=http://$HOST_IP:2379

# dtan4-paus-edc8df8
REPOSITORY=$(echo "$1")
REVISION=$(echo "$2")
USER_NAME=$(echo "$3")
PROJECT_NAME=$USER_NAME-$REPOSITORY-$(echo $REVISION | awk '{ print substr($0, 0, 8) }')

BASE_DOMAIN=`cat /base-domain`

exit_code=0

# echo "Repository: $1"
# echo "Revision: $2"
# echo "Username: $3"
# echo "Fingerprint: $4"

mkdir -p /tmp/build/$USER_NAME/$PROJECT_NAME || true
cat | tar -x -C /tmp/build/$USER_NAME/$PROJECT_NAME

# NOTE:
# 各userそれぞれ最新3件のみコンテナが立ち上がっている状態にする
cd /tmp/build/$USER_NAME

PROJECT_COUNT=$(ls -1 | wc -l)
if [[ $PROJECT_COUNT -gt 3 ]]; then
  OLD_PROJECT=$(ls -rt | head -n 1)
  cd /tmp/build/$USER_NAME/$OLD_PROJECT
  docker-compose -p $OLD_PROJECT stop > /dev/null
  docker-compose -p $OLD_PROJECT rm > /dev/null
  cd $BASE_DIR
  rm -rf /tmp/build/$USER_NAME/$OLD_PROJECT
fi

cd /tmp/build/$USER_NAME/$PROJECT_NAME

# username/projectname
IMAGE_TAG=$USER_NAME/$REPOSITORY

if [[ -f docker-compose.yml ]]; then
  echo "=====> docker-compose.yml was detected"

  echo "=====> Building Dockerfile..."
  docker build -t $IMAGE_TAG build .

  echo "=====> Pushing image..."
  docker push localhost:5000/$IMAGE_TAG

  echo "=====> Building..."
  sed -i -e "s/build:.*/image: localhost:5000\/$USER_NAME\/$REPOSITORY/g" docker-compose.yml
  docker-compose -p $PROJECT_NAME build

  echo "=====> Pulling..."
  docker-compose -p $PROJECT_NAME pull

  echo "=====> Deploying..."
  docker-compose -p $PROJECT_NAME up -d

  web_container_id=`docker-compose -p $PROJECT_NAME ps -q web`
  web_container_host_ip=`docker inspect $web_container_id | jq -r '.[0].NetworkSettings.Ports | .["8080/tcp"] | .[0].HostIp'`
  web_container_port=`docker inspect $web_container_id | jq -r '.[0].NetworkSettings.Ports | .["8080/tcp"] | .[0].HostPort'`

  etcdctl set /vulcand/backends/$PROJECT_NAME/backend '{"Type": "http"}' > /dev/null
  etcdctl set /vulcand/backends/$PROJECT_NAME/servers/$web_container_id "{\"URL\": \"http://$web_container_host_ip:$web_container_port\"}" > /dev/null
  domain=$(etcdctl set /vulcand/frontends/$PROJECT_NAME/frontend "{\"Type\": \"http\", \"BackendId\": \"$PROJECT_NAME\", \"Route\": \"Host(\`$PROJECT_NAME.$BASE_DOMAIN\`) && PathRegexp(\`/\`)\"}" \
              | jq -r .Route | sed -E "s/Host\(\`(.+?)\`\).+/\1/")

  echo "=====> $REPOSITORY was deployed at http://$domain/"

  # username.wantedlyapp.com
  domain=$(etcdctl set /vulcand/frontends/$USER_NAME/frontend "{\"Type\": \"http\", \"BackendId\": \"$PROJECT_NAME\", \"Route\": \"Host(\`$USER_NAME.$BASE_DOMAIN\`) && PathRegexp(\`/\`)\"}" \
              | jq -r .Route | sed -E "s/Host\(\`(.+?)\`\).+/\1/")

  echo "=====> $REPOSITORY was deployed at http://$domain/"
else
  echo "=====> docker-compose.yml was NOT found!"
  exit_code=1
fi

exit $exit_code
